### ISSUE TITLE
Bach10 link seems dead

### ISSUE THREAD

**Issue by carlthome** [ismir/mir-datasets#26] opened 2020-03-16 16:13 UTC
https://github.com/ismir/mir-datasets/blob/74c0fe46023098f0894d04eeb949407108328d2a/mir-datasets.yaml#L64 leads to https://interactiveaudiolab.github.io/ with no dataset in sight.

Similarly, https://users.cs.northwestern.edu/~zdu459/Bach10 is now a 404.

**Comment by alexanderlerch** [comment] 2020-03-16 17:26
You should be able to find it at http://www2.ece.rochester.edu/projects/air/resource.html

Best,
Alexander

www.AudioContentAnalysis.org<http://www.audiocontentanalysis.org/>
www.musicinformatics.gatech.edu<http://www.musicinformatics.gatech.edu/>
www.gtcmt.gatech.edu<http://www.gtcmt.gatech.edu>

**Comment by lostanlen** [comment] 2020-04-05 07:17
This broken link is fixed on @alexanderlerch 's branch `lerch_updates`
See commit : https://github.com/ismir/mir-datasets/commit/92bf8df4df74adaa8b4918267b25cf6dfed9cd6a

@alexanderlerch perhaps you can make a PR to the master branch and close this issue?

**Comment by alexanderlerch** [comment] 2020-04-05 15:36
Hm, ok, that's a bit of a mess because of the experimental changes in the branch (see issue #3 ), also: there have been quite a few dataset updates since the branch was created - should these all be merged in one pull request?

**Comment by lostanlen** [comment] 2020-04-05 16:45
@alexanderlerch i have no problem with closing multiple issues with a single PR :)
it's just that i only discovered your branch today. i would be in favor of opening the PR early so that other people see that the issue is being attended

**Comment by alexanderlerch** [comment] 2020-04-05 18:12
@lostanlen  Well, I have to roll back the references that I added for trying to address #3 before anything can be merged. I'll look into this.

**Comment by stefan-balke** [comment] 2020-07-06 18:56
Fixed through #27 

https://github.com/ismir/mir-datasets/blob/master/mir-datasets.yaml#L70

**Closed by stefan-balke** 2020-07-06 18:56 UTC

**Comment by Laubeee** [comment] 2023-11-13 17:27
new link is again down.

**Comment by carlthome** [comment] 2023-11-13 22:42
@Laubeee best to create a new issue since this was marked as completed three years ago.
